clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true

steps:
  build:
    image: debian
    when:
      branch:
        - ${CI_REPO_DEFAULT_BRANCH}
      event: [push, pull_request]
    commands: |
      apt-get update
      apt-get install -yy make gcc libfftw3-dev liblapacke-dev libpng-dev libopenblas-dev gfortran git
      make
      make utest

